-- Role: foodapp
-- DROP ROLE IF EXISTS foodapp;

CREATE ROLE foodapp WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:E9ejk4Tw0IR47U3wYJCWGg==$KpNiMhQWv7EE9IRpIzZ3deKAXwi+LvRy+craSPsNjR8=:a2SDjxJH7glC05RoG3BTDD0Vb17CNcGKbOr85Dslph0=';
